### PR TITLE
Added -s option to skip ROM creation. Useful when used in conjuction with -A

### PR DESCRIPTION
**Pull request by jotego**
I often need to create ARC files in mass but I don't need the ROM output.

### CODE REVIEW

**Comment by sebdel** [comment]
Please separate your PR. I'll take the part that adds a "-s" option but not the part that uses your own implementation of strcasestr :)

**Comment by jotego** [comment]
Haha, I didn't know about strcasestr! I'll change it.

**Comment by jotego** [comment]
Ok. I have changed it to strcasestr, but it doesn't seem to be defined in string.h

**Comment by sebdel** [comment]
strcasestr needs _GNU_SOURCE, it's bad for cross compiling. Sorry for the bad advice, I fixed it in the next commit.

**Pull request merged**
