### PR TITLE
Replaced characters in ARC filename which FAT32 does not support

### PR DESCRIPTION
**Pull request by jotego**
Characters such as : and ? which are ok for displaying in the OSD or for some filesystems cannot be used on ARC files that target FAT32 filesystems.

### CODE REVIEW

**Review by sebdel — COMMENTED** [review]
I'll take it, but can you move the function make_fat32_compatible to utils.c/utils.h instead?

**Comment by jotego** [comment]
Done. Can you merge it now? I'd like to try adding the default value for ARC files next.

**Comment by jotego** [comment]
I have added the default value for ARC files now too

**Comment by gyurco** [comment]
Maybe would be good to include the full 32 bit in the ARC file, just the firmware will ignore bit 0.
Then bit1-7 can also have a default value.

**Comment by gyurco** [comment]
One more thing: the ini parsers use strtoul with 0 base, it needs 0x prefix for hex values:
 strtoul(&(buf[i]), NULL, 0);
Can you add that too, please?

**Comment by jotego** [comment]
I have added the 0x prefix now and the full 32bit value will be dumped.

**Pull request merged**
